

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:HYW@db:3306/houyanwu

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=HYW
      - MYSQL_DATABASE=houyanwu
    ports:
      - "3306:3306"

volumes:
  db_data: